# Server settings
server.port=8080

# MongoDB settings
spring.data.mongodb.uri=mongodb+srv://ashishsuryavanshi858_db_user:healthmitra@cluster0.rhseqaw.mongodb.net/
spring.data.mongodb.database=healthmitra